### ISSUE TITLE
Updates?

### ISSUE THREAD

**Issue by aadrian** [gitbucket-plugins/gitbucket-explorer-plugin#11]
Hi,

Any chance updating the project to work with newer versions of GitBucket?

Or at least if you can't update it anymore, move/give it to https://github.com/gitbucket-plugins so that other users can update it more often?

Thank you.

**Comment by tomoki1207** [comment]
@aadrian 
Thank you the suggestion, I'll entrust you to the updates.
I'll transfer this repo soon.

Thank you.

**Comment by tomoki1207** [comment]
@aadrian 
I want to move ownership, can you remove forked repository from gitbucket-plugins?
Or tell me how to move ownership after clonined

**Comment by aadrian** [comment]
@tomoki1207 thank you very much for the nice project.

Unfortunately I don't have the rights to remove the clone from that org, so I **renamed** the clone to xxx_clone (until I merge the changes I've already made, and @takezoe can than delete the clone ). 

Now you should be able to transfer it without problems from "Settings"/"Danger Zone"/"Transfer Ownership".

**Comment by tomoki1207** [comment]
I failed to transfer.
Maybe It can't duplicate fork regardless repository name...

![screenshot-2017-9-4 tomoki1207 gitbucket-explorer-plugin](https://user-images.githubusercontent.com/3643499/30015898-b24dfe9e-918d-11e7-8981-77b3b6571d36.png)

**Comment by aadrian** [comment]
@tomoki1207 I was able now to delete the repo :) ! Please try again.

**Comment by tomoki1207** [comment]
@aadrian Thanks.
But It still failed with a message "You don’t have the permission to create repositories on gitbucket-plugins".
It may makes possible that it move to under your account. And then move to gitbucket-plugin group from your account.

So, can you remove a forked repo from your account?

**Comment by aadrian** [comment]
@tomoki1207 
> It may makes possible that it move to under your account. And then move to gitbucket-plugin 
> group from your account.

good idea!

> So, can you remove a forked repo from your account?

I removed my fork.

**Comment by tomoki1207** [comment]
@aadrian 
I transferred ownership to you.
Please check it.

Thank you.

**Comment by aadrian** [comment]
@tomoki1207 
> I transferred ownership to you.

Unfortunately this doesn't seem to be succeeded yet :( .

> Please check it.

I've received no request to take over the owenership so far :( .

As a test, I'ver created a **test repo** and requested it to transfer to you. 

You should see something similar with gitbucket-explore-plugin, except with my user **aadrian** in it.
 
<img width="772" alt="screen shot 2017-09-05 at 09 40 15" src="https://user-images.githubusercontent.com/140953/30050357-7f37a276-921e-11e7-85b7-b6e2f0621d6b.png">

**Comment by aadrian** [comment]
@tomoki1207 now it seems that it worked!

Thank you very much for the project and for your support!
