### ISSUE TITLE
exception: java.lang.NoSuchMethodError: gitbucket.core.util.JGitUtil$.getFileList

### ISSUE THREAD

**Issue by zsmahi** [gitbucket-plugins/gitbucket-explorer-plugin#15]
Hello the Team

I'm new in gitbucket and explorer plugin. I've installed it this morning as explained in the readme file however the explorer tree is empty (see image below), and when expecting the code I've found that the issue was caused by an internal error 500 (an exception was thrown) the details of this exception is java.lang.NoSuchMethodError: gitbucket.core.util.JGitUtil$.getFileList

I use windows 10, tomcat 9 and gitbucket version 4.34.0

can you help me to solve this ? thanks in advance.

Here is the screenshot
![image](https://user-images.githubusercontent.com/2100091/89531415-7bf50700-d7f0-11ea-8887-0cffee4fd6b8.png)

and the trace of the exception 

> 

io.github.gitbucket.explorer.controllers.ExplorerControllerBase.$anonfun$explore$3(ExplorerController.scala:41)
--
gitbucket.core.util.SyntaxSugars$.defining(SyntaxSugars.scala:12)
io.github.gitbucket.explorer.controllers.ExplorerControllerBase.$anonfun$explore$2(ExplorerController.scala:39)
scala.Option.map(Option.scala:242)
io.github.gitbucket.explorer.controllers.ExplorerControllerBase.$anonfun$explore$1(ExplorerController.scala:38)
scala.util.Using$.resource(Using.scala:252)
io.github.gitbucket.explorer.controllers.ExplorerControllerBase.explore(ExplorerController.scala:36)
io.github.gitbucket.explorer.controllers.ExplorerControllerBase.$anonfun$$init$$4(ExplorerController.scala:32)
gitbucket.core.util.ReferrerAuthenticator.$anonfun$authenticate$4(Authenticator.scala:95)
scala.Option.map(Option.scala:242)
gitbucket.core.util.ReferrerAuthenticator.authenticate(Authenticator.scala:93)
gitbucket.core.util.ReferrerAuthenticator.referrersOnly(Authenticator.scala:87)
gitbucket.core.util.ReferrerAuthenticator.referrersOnly$(Authenticator.scala:87)
io.github.gitbucket.explorer.controllers.ExplorerController.referrersOnly(ExplorerController.scala:17)
io.github.gitbucket.explorer.controllers.ExplorerControllerBase.$anonfun$$init$$3(ExplorerController.scala:28)
org.scalatra.ScalatraBase.liftAction(ScalatraBase.scala:282)
org.scalatra.ScalatraBase.$anonfun$invoke$1(ScalatraBase.scala:276)
org.scalatra.ApiFormats.withRouteMultiParams(ApiFormats.scala:185)
org.scalatra.ApiFormats.withRouteMultiParams$(ApiFormats.scala:171)
gitbucket.core.controller.ControllerBase.withRouteMultiParams(ControllerBase.scala:35)
org.scalatra.ScalatraBase.invoke(ScalatraBase.scala:275)
org.scalatra.ScalatraBase.invoke$(ScalatraBase.scala:274)
gitbucket.core.controller.ControllerBase.invoke(ControllerBase.scala:35)
org.scalatra.ScalatraBase.$anonfun$runRoutes$3(ScalatraBase.scala:250)
scala.Option.flatMap(Option.scala:283)
org.scalatra.ScalatraBase.$anonfun$runRoutes$1(ScalatraBase.scala:248)
scala.collection.immutable.Stream.flatMap(Stream.scala:202)
org.scalatra.ScalatraBase.runRoutes(ScalatraBase.scala:247)
org.scalatra.ScalatraBase.runRoutes$(ScalatraBase.scala:245)
gitbucket.core.controller.ControllerBase.runRoutes(ControllerBase.scala:35)
org.scalatra.ScalatraBase.runActions$1(ScalatraBase.scala:169)
org.scalatra.ScalatraBase.$anonfun$executeRoutes$6(ScalatraBase.scala:181)
scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
org.scalatra.ScalatraBase.cradleHalt(ScalatraBase.scala:201)
org.scalatra.ScalatraBase.executeRoutes(ScalatraBase.scala:181)
org.scalatra.ScalatraBase.executeRoutes$(ScalatraBase.scala:150)
gitbucket.core.controller.ControllerBase.executeRoutes(ControllerBase.scala:35)
org.scalatra.ScalatraBase.$anonfun$handle$1(ScalatraBase.scala:123)
scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
scala.util.DynamicVariable.withValue(DynamicVariable.scala:59)
org.scalatra.DynamicScope.withResponse(DynamicScope.scala:75)
org.scalatra.DynamicScope.withResponse$(DynamicScope.scala:73)
gitbucket.core.controller.ControllerBase.withResponse(ControllerBase.scala:35)
org.scalatra.DynamicScope.$anonfun$withRequestResponse$1(DynamicScope.scala:55)
scala.util.DynamicVariable.withValue(DynamicVariable.scala:59)
org.scalatra.DynamicScope.withRequest(DynamicScope.scala:66)
org.scalatra.DynamicScope.withRequest$(DynamicScope.scala:64)
gitbucket.core.controller.ControllerBase.withRequest(ControllerBase.scala:35)
org.scalatra.DynamicScope.withRequestResponse(DynamicScope.scala:54)
org.scalatra.DynamicScope.withRequestResponse$(DynamicScope.scala:52)
gitbucket.core.controller.ControllerBase.withRequestResponse(ControllerBase.scala:35)
org.scalatra.ScalatraBase.handle(ScalatraBase.scala:123)
org.scalatra.ScalatraBase.handle$(ScalatraBase.scala:119)
gitbucket.core.controller.ControllerBase.org$scalatra$servlet$ServletBase$$super$handle(ControllerBase.scala:35)
org.scalatra.servlet.ServletBase.handle(ServletBase.scala:42)
org.scalatra.servlet.ServletBase.handle$(ServletBase.scala:35)
gitbucket.core.controller.ControllerBase.org$scalatra$FlashMapSupport$$super$handle(ControllerBase.scala:35)
org.scalatra.FlashMapSupport.$anonfun$handle$1(FlashMap.scala:197)
scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
scala.util.DynamicVariable.withValue(DynamicVariable.scala:59)
org.scalatra.DynamicScope.withRequest(DynamicScope.scala:66)
org.scalatra.DynamicScope.withRequest$(DynamicScope.scala:64)
gitbucket.core.controller.ControllerBase.withRequest(ControllerBase.scala:35)
org.scalatra.FlashMapSupport.handle(FlashMap.scala:172)
org.scalatra.FlashMapSupport.handle$(FlashMap.scala:171)
gitbucket.core.controller.ControllerBase.handle(ControllerBase.scala:35)
org.scalatra.ScalatraFilter.$anonfun$doFilter$1(ScalatraFilter.scala:41)
scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
scala.util.DynamicVariable.withValue(DynamicVariable.scala:59)
org.scalatra.ScalatraFilter.doFilter(ScalatraFilter.scala:41)
org.scalatra.ScalatraFilter.doFilter$(ScalatraFilter.scala:36)
gitbucket.core.controller.ControllerBase.doFilter(ControllerBase.scala:73)
gitbucket.core.servlet.PluginControllerFilter.$anonfun$process$2(PluginControllerFilter.scala:39)
gitbucket.core.servlet.PluginControllerFilter.$anonfun$process$2$adapted(PluginControllerFilter.scala:32)
scala.collection.immutable.List.foreach(List.scala:305)
gitbucket.core.servlet.PluginControllerFilter.process(PluginControllerFilter.scala:32)
gitbucket.core.servlet.ControllerFilter.doFilter(CompositeScalatraFilter.scala:25)
org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
org.scalatra.ScalatraFilter.$anonfun$doNotFound$1(ScalatraFilter.scala:79)
scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
org.scalatra.ScalatraBase.$anonfun$executeRoutes$5(ScalatraBase.scala:172)
scala.Option.getOrElse(Option.scala:201)
org.scalatra.ScalatraBase.$anonfun$executeRoutes$3(ScalatraBase.scala:172)
scala.Option.getOrElse(Option.scala:201)
org.scalatra.ScalatraBase.runActions$1(ScalatraBase.scala:172)
org.scalatra.ScalatraBase.$anonfun$executeRoutes$6(ScalatraBase.scala:181)
scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
org.scalatra.ScalatraBase.cradleHalt(ScalatraBase.scala:201)
org.scalatra.ScalatraBase.executeRoutes(ScalatraBase.scala:181)
org.scalatra.ScalatraBase.executeRoutes$(ScalatraBase.scala:150)
gitbucket.core.controller.ControllerBase.executeRoutes(ControllerBase.scala:35)
org.scalatra.ScalatraBase.$anonfun$handle$1(ScalatraBase.scala:123)
scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
scala.util.DynamicVariable.withValue(DynamicVariable.scala:59)
org.scalatra.DynamicScope.withResponse(DynamicScope.scala:75)
org.scalatra.DynamicScope.withResponse$(DynamicScope.scala:73)
gitbucket.core.controller.ControllerBase.withResponse(ControllerBase.scala:35)
org.scalatra.DynamicScope.$anonfun$withRequestResponse$1(DynamicScope.scala:55)
scala.util.DynamicVariable.withValue(DynamicVariable.scala:59)
org.scalatra.DynamicScope.withRequest(DynamicScope.scala:66)
org.scalatra.DynamicScope.withRequest$(DynamicScope.scala:64)
gitbucket.core.controller.ControllerBase.withRequest(ControllerBase.scala:35)
org.scalatra.DynamicScope.withRequestResponse(DynamicScope.scala:54)
org.scalatra.DynamicScope.withRequestResponse$(DynamicScope.scala:52)
gitbucket.core.controller.ControllerBase.withRequestResponse(ControllerBase.scala:35)
org.scalatra.ScalatraBase.handle(ScalatraBase.scala:123)
org.scalatra.ScalatraBase.handle$(ScalatraBase.scala:119)
gitbucket.core.controller.ControllerBase.org$scalatra$servlet$ServletBase$$super$handle(ControllerBase.scala:35)
org.scalatra.servlet.ServletBase.handle(ServletBase.scala:42)
org.scalatra.servlet.ServletBase.handle$(ServletBase.scala:35)
gitbucket.core.controller.ControllerBase.org$scalatra$FlashMapSupport$$super$handle(ControllerBase.scala:35)
org.scalatra.FlashMapSupport.$anonfun$handle$1(FlashMap.scala:197)
scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
scala.util.DynamicVariable.withValue(DynamicVariable.scala:59)
org.scalatra.DynamicScope.withRequest(DynamicScope.scala:66)
org.scalatra.DynamicScope.withRequest$(DynamicScope.scala:64)
gitbucket.core.controller.ControllerBase.withRequest(ControllerBase.scala:35)
org.scalatra.FlashMapSupport.handle(FlashMap.scala:172)
org.scalatra.FlashMapSupport.handle$(FlashMap.scala:171)
gitbucket.core.controller.ControllerBase.handle(ControllerBase.scala:35)
org.scalatra.ScalatraFilter.$anonfun$doFilter$1(ScalatraFilter.scala:41)
scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
scala.util.DynamicVariable.withValue(DynamicVariable.scala:59)
org.scalatra.ScalatraFilter.doFilter(ScalatraFilter.scala:41)
org.scalatra.ScalatraFilter.doFilter$(ScalatraFilter.scala:36)
gitbucket.core.controller.ControllerBase.doFilter(ControllerBase.scala:73)
org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
gitbucket.core.servlet.TransactionFilter.$anonfun$doFilter$1(TransactionFilter.scala:39)
gitbucket.core.servlet.TransactionFilter.$anonfun$doFilter$1$adapted(TransactionFilter.scala:30)
com.github.takezoe.slick.blocking.BlockingJdbcProfile$BlockingAPI$BlockingDatabase.$anonfun$withTransaction$2(BlockingProfile.scala:207)
slick.JdbcProfileBlockingSession$BlockingSession.withTransaction(TransactionalJdbcBackend.scala:26)
com.github.takezoe.slick.blocking.BlockingJdbcProfile$BlockingAPI$BlockingDatabase.$anonfun$withTransaction$1(BlockingProfile.scala:207)
com.github.takezoe.slick.blocking.BlockingJdbcProfile$BlockingAPI$BlockingDatabase.withSession(BlockingProfile.scala:200)
com.github.takezoe.slick.blocking.BlockingJdbcProfile$BlockingAPI$BlockingDatabase.withTransaction(BlockingProfile.scala:207)
gitbucket.core.servlet.TransactionFilter.doFilter(TransactionFilter.scala:30)
org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541)
org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:690)
org.apache.catalina.valves.RequestFilterValve.process(RequestFilterValve.java:348)
org.apache.catalina.valves.RemoteAddrValve.invoke(RemoteAddrValve.java:53)
org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:373)
org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1589)
org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
java.lang.Thread.run(Unknown Source)

**Comment by takezoe** [comment]
Thanks for reporting! There is a binary incompatibility in GitBucket 4.43.0. We need to update this plugin.

**Comment by zsmahi** [comment]
@takezoe thanks for your answer, so is the fix a priority or should I wait a moment until it'll be fixed ?

**Comment by takezoe** [comment]
Released a fixed version: https://github.com/gitbucket-plugins/gitbucket-explorer-plugin/releases/tag/8.0.0
