### ISSUE TITLE
No tree showing (wrong path ?)

### ISSUE THREAD

**Issue by zexxar** [gitbucket-plugins/gitbucket-explorer-plugin#2]
Hello,

I wanted to use this plugin for our gitbucket, but somehow it isn't working properly because the tree is not shown and if I hover over the "Files" the link it shows also doesn't look quite correct. And I suppose that this is also the problem why no files are shown because of the wrong path (see screenshot bottom). 

![gitbucket_explorer](https://cloud.githubusercontent.com/assets/4499859/22918931/4e297b68-f28d-11e6-8ea8-4aa02e77e806.png)

The basepath that is defined in Gitbucket is https://10.157.133.83/gitbucket and eerything else works just fine.

Do you already know this problem and maybe already have a fix for this because I would love to use this plugin.

Kind Regards
zexxar

**Comment by tomoki1207** [comment]
@zexxar Thank you for detail reporting.
It looks caused by basepath settings.
It'll fix on v1.0.2.

**Comment by tomoki1207** [comment]
@zexxar 
Fixed it on [v1.0.2](https://github.com/tomoki1207/gitbucket-explorer-plugin/releases/tag/1.0.2). Could you try it?

**Comment by zexxar** [comment]
@tomoki1207 I just checked it again and now it is working just fine.  :) 

Thank you very much for fixing this problem so fast.
