### ISSUE TITLE
Redirection to css file after login [BUG]

### ISSUE THREAD

**Issue by zexxar** [gitbucket-plugins/gitbucket-explorer-plugin#3]
Hi,

I just found another problem that I can also reproduce. After every loggin I'm getting redirected to this css file "https://10.157.133.83/gitbucket/plugin-assets/explorer/plugin-explorer.css" (Gitbucket BaseURL set to: https://10.157.133.83/gitbucket ). Also a colleague of mine could also reproduce this bug in Firefox and in Chrome. 

Do you have any fix for this.

Thanks in advance.
zexxar

**Comment by tomoki1207** [comment]
@zexxar 
Thank you for reporting.
This might be happen when denied anonymous access.
It solved on v1.0.3.

**Comment by tomoki1207** [comment]
@zexxar 
Thank you for reporting.
This might be happen when denied anonymous access.
It solved on v1.0.3.

**Comment by zexxar** [comment]
@tomoki1207 
I just tried v1.0.3 and I didn't get that error anymore now I'm always redirect to the main page as it should be. 
Thanks a lot fo the fast fix. :)
