### ISSUE TITLE
Plugin not works. Version of the plugin is 2.0.0.

### ISSUE THREAD

**Issue by himeyon** [gitbucket-plugins/gitbucket-explorer-plugin#7]
After upgrading the version of gitbucket to 4.11, plugin not works. Version of the plugin is 2.0.0.
![image](https://cloud.githubusercontent.com/assets/4468822/24636915/6d2f448c-1918-11e7-88ce-e4a33c0561ef.png)

**Comment by aadrian** [comment]
@himeyon a new version of this plug-in needs to be released for GitBucket 4.11.0 I suppose.

**Comment by tomoki1207** [comment]
Thank you for reporting.
We supported GitBucket 4.11 at 3.0.0.
